-- MySQL Script generated by MySQL Workbench
-- Tue May 26 19:48:22 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_imob
-- -----------------------------------------------------
-- banco de dados criado para o sistema Imob com o uso da linguagem java por Lucas Thome da Silva na data 21/05/2020
DROP SCHEMA IF EXISTS `bd_imob` ;

-- -----------------------------------------------------
-- Schema bd_imob
--
-- banco de dados criado para o sistema Imob com o uso da linguagem java por Lucas Thome da Silva na data 21/05/2020
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_imob` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
SHOW WARNINGS;
USE `bd_imob` ;

-- -----------------------------------------------------
-- Table `tb_Avista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_Avista` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_Avista` (
  `id_Avista` INT NOT NULL AUTO_INCREMENT,
  `id_Codigo_Avista` INT NULL,
  `id_Cliente` INT NULL,
  `data_Pagamento` DATE NULL,
  PRIMARY KEY (`id_Avista`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_Cartao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_Cartao` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_Cartao` (
  `id_Cartao` INT NOT NULL AUTO_INCREMENT,
  `id_Codigo_Cartao` INT NULL,
  `id_Cliente` INT NULL,
  `numero_Cartao` VARCHAR(45) NULL,
  `data_Vencimento_Cartao` DATE NULL,
  `data_Recebimento` DATE NULL,
  `tipo_Cartao` VARCHAR(45) NULL,
  `valor_Recebimento` DOUBLE NULL,
  `anotacoes` LONGTEXT NULL,
  PRIMARY KEY (`id_Cartao`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_Cheque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_Cheque` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_Cheque` (
  `id_Cheque` INT NOT NULL AUTO_INCREMENT,
  `id_Codigo_Cheque` INT NULL,
  `banco` VARCHAR(45) NULL,
  `id_Cliente` INT NULL,
  `numero_Cheque` VARCHAR(45) NULL,
  `referente_Pagamento` VARCHAR(150) NULL,
  `a_vista` VARCHAR(5) NULL,
  `parcelado` VARCHAR(5) NULL,
  `quantidade_Vezes` INT NULL,
  `compensado` VARCHAR(5) NULL,
  `data_Cheque` DATE NULL,
  `data_Recebimento` DATE NULL,
  `data_Abertura_Conta` DATE NULL,
  `anotacoes` LONGTEXT NULL,
  PRIMARY KEY (`id_Cheque`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_Deposito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_Deposito` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_Deposito` (
  `id_Deposito` INT NOT NULL AUTO_INCREMENT,
  `id_Codigo_Deposito` INT NULL,
  `id_Cliente` INT NULL,
  `data_Deposito` DATE NULL,
  `codigo_Identificacao` VARCHAR(45) NULL,
  `tipo_Deposito` VARCHAR(45) NULL,
  `valor_Deposito` DOUBLE NULL,
  `confirmacao_Deposito` VARCHAR(5) NULL,
  `deposito_Realizado` VARCHAR(5) NULL,
  `anotacoes` LONGTEXT NULL,
  PRIMARY KEY (`id_Deposito`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_cidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_cidades` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_cidades` (
  `id_Cidade` INT NOT NULL AUTO_INCREMENT,
  `nome_Cidade` VARCHAR(150) NULL,
  `tb_estados_id_Estado` INT NOT NULL,
  PRIMARY KEY (`id_Cidade`, `tb_estados_id_Estado`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_cliente_pessoa_fisica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_cliente_pessoa_fisica` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_cliente_pessoa_fisica` (
  `id_ClientePF` INT NOT NULL AUTO_INCREMENT,
  `id_Codigo_ClientePF` INT NULL,
  `status_Comprador` VARCHAR(45) NULL,
  `status_Vendedor` VARCHAR(45) NULL,
  `status_Locatario` VARCHAR(45) NULL,
  `status_Locador` VARCHAR(45) NULL,
  `tb_pessoa_fisica_id_PessoaF` INT NOT NULL,
  `tb_pessoa_fisica_tb_pessoa_id_Pessoa` INT NOT NULL,
  PRIMARY KEY (`id_ClientePF`, `tb_pessoa_fisica_id_PessoaF`, `tb_pessoa_fisica_tb_pessoa_id_Pessoa`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_cliente_pessoa_juridica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_cliente_pessoa_juridica` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_cliente_pessoa_juridica` (
  `id_ClientePJ` INT NOT NULL AUTO_INCREMENT,
  `id_Codigo_ClientePJ` INT NULL,
  `status_Comprador` VARCHAR(45) NULL,
  `status_Vendedor` VARCHAR(45) NULL,
  `status_Locatario` VARCHAR(45) NULL,
  `status_Locador` VARCHAR(45) NULL,
  `tb_pessoa_juridica_id_PessoaPJ` INT NOT NULL,
  `tb_pessoa_juridica_tb_pessoa_id_Pessoa` INT NOT NULL,
  PRIMARY KEY (`id_ClientePJ`, `tb_pessoa_juridica_id_PessoaPJ`, `tb_pessoa_juridica_tb_pessoa_id_Pessoa`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_corretor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_corretor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_corretor` (
  `id_Corretor` INT NOT NULL AUTO_INCREMENT,
  `id_Codigo_Corretor` INT NULL,
  `numero_Creci` INT NULL,
  `tb_pessoa_fisica_id_PessoaF` INT NOT NULL,
  `tb_pessoa_fisica_tb_pessoa_id_Pessoa` INT NOT NULL,
  `tb_pagamento_comissao_id_Pag_Comissao` INT NOT NULL,
  PRIMARY KEY (`id_Corretor`, `tb_pessoa_fisica_id_PessoaF`, `tb_pessoa_fisica_tb_pessoa_id_Pessoa`, `tb_pagamento_comissao_id_Pag_Comissao`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_emails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_emails` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_emails` (
  `id_Email` INT NOT NULL AUTO_INCREMENT,
  `id_Codigo_Email` INT NULL,
  `tipo_Email` VARCHAR(45) NULL,
  `email` VARCHAR(150) NULL,
  `site` VARCHAR(150) NULL,
  `tb_pessoa_id_Pessoa` INT NOT NULL,
  PRIMARY KEY (`id_Email`, `tb_pessoa_id_Pessoa`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_enderecos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_enderecos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_enderecos` (
  `id_Endereco` INT NOT NULL AUTO_INCREMENT,
  `tipo_Logradouro` VARCHAR(100) NULL,
  `logradouro` VARCHAR(100) NULL,
  `numero_Logradouro` VARCHAR(45) NULL,
  `numero_Apartamento` VARCHAR(45) NULL,
  `andar_Apartamento` VARCHAR(45) NULL,
  `bloco_Apartamento` VARCHAR(45) NULL,
  `complemento` VARCHAR(45) NULL,
  `cep` VARCHAR(45) NULL,
  `latitude` VARCHAR(45) NULL,
  `longitude` VARCHAR(45) NULL,
  `referencias_Endereco` LONGTEXT NULL,
  `tb_cidades_id_Cidade` INT NOT NULL,
  `tb_cidades_tb_estados_id_Estado` INT NOT NULL,
  `tb_pessoa_id_Pessoa` INT NOT NULL,
  PRIMARY KEY (`id_Endereco`, `tb_cidades_id_Cidade`, `tb_cidades_tb_estados_id_Estado`, `tb_pessoa_id_Pessoa`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_estados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_estados` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_estados` (
  `id_Estado` INT NOT NULL AUTO_INCREMENT,
  `nome_Estado` VARCHAR(45) NULL,
  `sigla_Estado` VARCHAR(5) NULL,
  PRIMARY KEY (`id_Estado`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_imobiliaria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_imobiliaria` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_imobiliaria` (
  `id_Imobiliaria` INT NOT NULL AUTO_INCREMENT,
  `id_Codigo_Imobiliaria` INT NULL,
  `numero_Creci` INT NULL,
  `tb_pessoa_juridica_id_PessoaPJ` INT NOT NULL,
  `tb_pessoa_juridica_tb_pessoa_id_Pessoa` INT NOT NULL,
  `tb_pagamento_comissao_id_Pag_Comissao` INT NOT NULL,
  PRIMARY KEY (`id_Imobiliaria`, `tb_pessoa_juridica_id_PessoaPJ`, `tb_pessoa_juridica_tb_pessoa_id_Pessoa`, `tb_pagamento_comissao_id_Pag_Comissao`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_imovel_geral`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_imovel_geral` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_imovel_geral` (
  `id_Imovel` INT NOT NULL AUTO_INCREMENT,
  `id_Codigo_Imovel` INT NULL,
  `numero_Matricula` VARCHAR(150) NULL,
  `area_Total` INT NULL,
  `status_Venda` VARCHAR(45) NULL,
  `status_Locacao` VARCHAR(45) NULL,
  `tipo_Imovel` VARCHAR(45) NULL,
  `fotos` VARCHAR(45) NULL,
  `qualidade_Localizacao` VARCHAR(45) NULL,
  `qualidade_Acesso` VARCHAR(45) NULL,
  `anotacoes` LONGTEXT NULL,
  `tb_enderecos_id_Endereco` INT NOT NULL,
  `tb_enderecos_tb_cidades_id_Cidade` INT NOT NULL,
  `tb_enderecos_tb_cidades_tb_estados_id_Estado` INT NOT NULL,
  `tb_enderecos_tb_pessoa_id_Pessoa` INT NOT NULL,
  PRIMARY KEY (`id_Imovel`, `tb_enderecos_id_Endereco`, `tb_enderecos_tb_cidades_id_Cidade`, `tb_enderecos_tb_cidades_tb_estados_id_Estado`, `tb_enderecos_tb_pessoa_id_Pessoa`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_imovel_rural`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_imovel_rural` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_imovel_rural` (
  `id_ImovelR` INT NOT NULL AUTO_INCREMENT,
  `numero_Itr` VARCHAR(45) NULL,
  `area_Total` INT NULL,
  `unidade_Area_Total` VARCHAR(45) NULL,
  `area_App` INT NULL,
  `area_Utilizavel` INT NULL,
  `tem_Curral` VARCHAR(5) NULL,
  `tem_Casa_Sede` VARCHAR(5) NULL,
  `tem_Casa_Funcionarios` VARCHAR(5) NULL,
  `tem_Represa` VARCHAR(5) NULL,
  `tem_Poco_Artesiano` VARCHAR(5) NULL,
  `tem_Rio` VARCHAR(5) NULL,
  `tb_imovel_geral_id_Imovel` INT NOT NULL,
  `tb_imovel_geral_tb_enderecos_id_Endereco` INT NOT NULL,
  `tb_imovel_geral_tb_enderecos_tb_cidades_id_Cidade` INT NOT NULL,
  `tb_imovel_geral_tb_enderecos_tb_cidades_tb_estados_id_Estado` INT NOT NULL,
  `tb_imovel_geral_tb_enderecos_tb_pessoa_id_Pessoa` INT NOT NULL,
  PRIMARY KEY (`id_ImovelR`, `tb_imovel_geral_id_Imovel`, `tb_imovel_geral_tb_enderecos_id_Endereco`, `tb_imovel_geral_tb_enderecos_tb_cidades_id_Cidade`, `tb_imovel_geral_tb_enderecos_tb_cidades_tb_estados_id_Estado`, `tb_imovel_geral_tb_enderecos_tb_pessoa_id_Pessoa`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_imovel_urbano`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_imovel_urbano` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_imovel_urbano` (
  `id_ImovelU` INT NOT NULL AUTO_INCREMENT,
  `numero_Iptu` VARCHAR(45) NULL,
  `area_Total` INT NULL,
  `area_Constuida` INT NULL,
  `qtd_Banheiros` INT NULL,
  `qtd_Dormitorios` INT NULL,
  `qtd_Salas` INT NULL,
  `qtd_Suites` INT NULL,
  `qtd_Carros` INT NULL,
  `tem_Garagem` VARCHAR(5) NULL,
  `tem_Churrasqueira` VARCHAR(5) NULL,
  `tb_imovel_geral_id_Imovel` INT NOT NULL,
  `tb_imovel_geral_tb_enderecos_id_Endereco` INT NOT NULL,
  `tb_imovel_geral_tb_enderecos_tb_cidades_id_Cidade` INT NOT NULL,
  `tb_imovel_geral_tb_enderecos_tb_cidades_tb_estados_id_Estado` INT NOT NULL,
  `tb_imovel_geral_tb_enderecos_tb_pessoa_id_Pessoa` INT NOT NULL,
  PRIMARY KEY (`id_ImovelU`, `tb_imovel_geral_id_Imovel`, `tb_imovel_geral_tb_enderecos_id_Endereco`, `tb_imovel_geral_tb_enderecos_tb_cidades_id_Cidade`, `tb_imovel_geral_tb_enderecos_tb_cidades_tb_estados_id_Estado`, `tb_imovel_geral_tb_enderecos_tb_pessoa_id_Pessoa`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_login` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_login` (
  `id_Login` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(150) NULL,
  `senha` VARCHAR(45) NULL,
  `permissao` VARCHAR(45) NULL,
  `data_Login` DATE NULL,
  `time_Login` VARCHAR(45) NULL,
  `tb_pessoa_fisica_id_PessoaF` INT NOT NULL,
  `tb_pessoa_fisica_tb_pessoa_id_Pessoa` INT NOT NULL,
  PRIMARY KEY (`id_Login`, `tb_pessoa_fisica_id_PessoaF`, `tb_pessoa_fisica_tb_pessoa_id_Pessoa`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_pagamento_comissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_pagamento_comissao` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_pagamento_comissao` (
  `id_Pag_Comissao` INT NOT NULL AUTO_INCREMENT,
  `data_Venda_Locacao` DATE NULL,
  `data_Pagamento` DATE NULL,
  `codigo_Corretor_Imobiliaria` INT NULL,
  `codgigo_Pagador_Comissao` INT NULL,
  `condicoes` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `numero_Nota_Recibo` VARCHAR(45) NULL,
  `documentacao_Venda_Locacao` VARCHAR(45) NULL,
  `anotacoes` LONGTEXT NULL,
  PRIMARY KEY (`id_Pag_Comissao`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_pagamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_pagamentos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_pagamentos` (
  `id_Pagamento` INT NOT NULL AUTO_INCREMENT,
  `id_Codigo_Pagamento` INT NULL,
  `data_Pagamento` DATE NULL,
  `data_Vencimento_Pagamento` DATE NULL,
  `juros_Mensais` DOUBLE NULL,
  `juros_Multa` DOUBLE NULL,
  `id_Codigo_Cliente` INT NULL,
  `forma_Pagamento` VARCHAR(45) NULL,
  `valor_Pagamento` DOUBLE NULL,
  `valor_Desconto` DOUBLE NULL,
  `valor_Total_Pagamento` DOUBLE NULL,
  `numero_Documento_Pagamento` INT NULL,
  `id_Cliente` INT NULL,
  `id_Imovel` INT NULL,
  PRIMARY KEY (`id_Pagamento`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_pesquisa_cadastral`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_pesquisa_cadastral` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_pesquisa_cadastral` (
  `id_Pesquisa_Cadastral` INT NOT NULL AUTO_INCREMENT,
  `id_Codigo_Pesquisa_Cadastral` INT NULL,
  `data_Pesquisa` DATE NULL,
  `data_Proxima_Pesquisa` DATE NULL,
  `situacao_Pesquisa` VARCHAR(45) NULL,
  `tb_pessoa_id_Pessoa` INT NOT NULL,
  PRIMARY KEY (`id_Pesquisa_Cadastral`, `tb_pessoa_id_Pessoa`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_pessoa` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_pessoa` (
  `id_Pessoa` INT NOT NULL AUTO_INCREMENT,
  `id_Codigo_Pessoa` INT NULL,
  PRIMARY KEY (`id_Pessoa`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_pessoa_fisica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_pessoa_fisica` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_pessoa_fisica` (
  `id_PessoaF` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `sobrenome` VARCHAR(150) NULL,
  `cpf` VARCHAR(45) NULL,
  `rg` VARCHAR(45) NULL,
  `data_Nascimento` DATE NULL,
  `sexo` VARCHAR(5) NULL,
  `estado_Civil` VARCHAR(100) NULL,
  `regime_Bens` VARCHAR(100) NULL,
  `naturalidade` VARCHAR(100) NULL,
  `estado_Naturalidade` VARCHAR(5) NULL,
  `escolaridade` VARCHAR(100) NULL,
  `profissao` VARCHAR(100) NULL,
  `nome_Pai` VARCHAR(150) NULL,
  `nome_Mae` VARCHAR(150) NULL,
  `status_Cadastro` VARCHAR(45) NULL,
  `anotacoes` LONGTEXT NULL,
  `tb_pessoa_id_Pessoa` INT NOT NULL,
  PRIMARY KEY (`id_PessoaF`, `tb_pessoa_id_Pessoa`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_pessoa_juridica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_pessoa_juridica` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_pessoa_juridica` (
  `id_PessoaPJ` INT NOT NULL AUTO_INCREMENT,
  `razao_Social` VARCHAR(150) NULL,
  `nome_Fantasia` VARCHAR(150) NULL,
  `cnpj` VARCHAR(45) NULL,
  `inscricao_Estadual` VARCHAR(45) NULL,
  `isento_Inscricao_E` VARCHAR(5) NULL,
  `atividade_Principal` VARCHAR(150) NULL,
  `atividades_Secundarias` LONGTEXT NULL,
  `data_Abertura` DATE NULL,
  `anotacoes` LONGTEXT NULL,
  `status_Cadastro` VARCHAR(45) NULL,
  `tb_pessoa_id_Pessoa` INT NOT NULL,
  PRIMARY KEY (`id_PessoaPJ`, `tb_pessoa_id_Pessoa`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_prestador_servicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_prestador_servicos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_prestador_servicos` (
  `id_Prestador` INT NOT NULL AUTO_INCREMENT,
  `id_Codigo_Prestador` INT NULL,
  `id_Codigo_Servico` INT NULL,
  `tipo_Servico_Prestado` VARCHAR(150) NULL,
  `data_Inicial` DATE NULL,
  `data_Final` DATE NULL,
  `anotacoes` LONGTEXT NULL,
  `tb_pessoa_juridica_id_PessoaPJ` INT NOT NULL,
  `tb_pessoa_juridica_tb_pessoa_id_Pessoa` INT NOT NULL,
  PRIMARY KEY (`id_Prestador`, `tb_pessoa_juridica_id_PessoaPJ`, `tb_pessoa_juridica_tb_pessoa_id_Pessoa`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_telefones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_telefones` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_telefones` (
  `id_Telefone` INT NOT NULL AUTO_INCREMENT,
  `id_Codigo_Telefone` INT NULL,
  `telefone01` VARCHAR(45) NULL,
  `telefone02` VARCHAR(45) NULL,
  `celular01` VARCHAR(45) NULL,
  `celular02` VARCHAR(45) NULL,
  `tipo_Telefone` VARCHAR(45) NULL,
  `numero_Telefone` VARCHAR(45) NULL,
  `tb_pessoa_id_Pessoa` INT NOT NULL,
  PRIMARY KEY (`id_Telefone`, `tb_pessoa_id_Pessoa`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
